[bumpver]
current_version = "0.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "[bumpver] {new_version}"
commit = true
tag = false
push = false

[bumpver.file_patterns]
"README.md"  = [
    "{version}"
]
"version/version.go" = [
    "{version}"
]

